version: 2
jobs:
  build:
    docker:
      - image: docker:latest
      
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Run a Docker command
          command: docker run hello-world
